apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: meunginx
  serviceName: webserver
  replicas: 2
  template:
    metadata:
      labels:
        app: meunginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: nginx:1.21.3
          ports:
            - name: webports
              containerPort: 80
          volumeMounts:
            - mountPath: usr/share/nginx/html
              name: www
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi